# -*- coding: utf-8 -*-
"""cs194-data-visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5hZBp9tDdkUQCbEpFcTXSFLQwfHXUpX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_dir = "./flash_cleaned.csv"
df = pd.read_csv(data_dir)
df

fig1, ax1 = plt.subplots(figsize=(10, 6))

category_counts = df['attack_category'].value_counts().sort_values(ascending=False)
bars = ax1.bar(range(len(category_counts)), category_counts.values)

for i, (bar, value) in enumerate(zip(bars, category_counts.values)):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
             str(value), ha='center', va='bottom')

ax1.set_xlabel('Attack Category')
ax1.set_ylabel('Number of Attacks')
ax1.set_title('Flash-Loan Attacks by Category (2020-2025)')
ax1.set_xticks(range(len(category_counts)))
ax1.set_xticklabels(category_counts.index, rotation=45, ha='right')
ax1.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('chart1_attack_categories.png', dpi=300, bbox_inches='tight')
plt.show()

fig2, ax2 = plt.subplots(figsize=(10, 7))

protocol_losses = df.groupby('protocol_category')['loss_amount_usd'].sum().sort_values(ascending=True)
bars = ax2.barh(range(len(protocol_losses)), protocol_losses.values / 1e6)  # Convert to millions

for i, (bar, value) in enumerate(zip(bars, protocol_losses.values)):
    ax2.text(value / 1e6 + 10, bar.get_y() + bar.get_height()/2,
             f'${value/1e6:.0f}M', va='center')

ax2.set_yticks(range(len(protocol_losses)))
ax2.set_yticklabels(protocol_losses.index)
ax2.set_xlabel('Total Loss (USD Millions)')
ax2.set_ylabel('Protocol Category')
ax2.set_title('Total Losses by Protocol Category')
ax2.grid(axis='x', alpha=0.3)

plt.tight_layout()
plt.savefig('chart2_protocol_losses.png', dpi=300, bbox_inches='tight')
plt.show()

fig3, ax3_1 = plt.subplots(figsize=(10, 6))

# Prepare yearly data
year_stats = df.groupby('year').agg({
    'attack_category': 'count',
    'loss_amount_usd': 'sum'
}).reset_index()
year_stats.columns = ['year', 'attack_count', 'total_loss_usd']

# Primary axis: Attack counts (bars)
color1 = 'tab:blue'
ax3_1.set_xlabel('Year')
ax3_1.set_ylabel('Number of Attacks', color=color1)
bars = ax3_1.bar(year_stats['year'], year_stats['attack_count'],
                 color=color1, alpha=0.7, label='Attack Count')
ax3_1.tick_params(axis='y', labelcolor=color1)
ax3_1.set_xticks(year_stats['year'])

# Secondary axis: Total losses (line)
ax3_2 = ax3_1.twinx()
color2 = 'tab:orange'
ax3_2.set_ylabel('Total Loss (USD Millions)', color=color2)
line = ax3_2.plot(year_stats['year'], year_stats['total_loss_usd'] / 1e6,
                  color=color2, marker='o', linewidth=2,
                  markersize=8, label='Total Loss')
ax3_2.tick_params(axis='y', labelcolor=color2)

# Add value labels on line
for x, y in zip(year_stats['year'], year_stats['total_loss_usd'] / 1e6):
    ax3_2.text(x, y + 20, f'${y:.0f}M', ha='center', va='bottom',
               color=color2, fontsize=9)

ax3_1.set_title('Flash-Loan Attack Frequency and Impact Over Time')
ax3_1.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('chart3_temporal_trends.png', dpi=300, bbox_inches='tight')
plt.show()

